In [ ]:
import pandas as pd 
import re
df = pd.read_csv('seoul_gagu.csv')
df.size

6060

In [ ]:
df.head()

,동별(1),동별(2),2015,2015.1,2015.2,2015.3,2015.4,2015.5,2015.6,2015.7,...,2024.10,2024.11,2024.12,2024.13,2024.14,2024.15,2024.16,2024.17,2024.18,2024.19
0,동별(1),동별(2),총가구,총가구,총가구,총가구,일반가구,일반가구,일반가구,일반가구,...,집단가구,집단가구,집단가구,집단가구,집단가구,집단가구,외국인가구,외국인가구,외국인가구,외국인가구
1,동별(1),동별(2),소계,소계,소계,소계,소계,소계,소계,소계,...,비친족 6인이상 가구,비친족 6인이상 가구,집단시설가구,집단시설가구,집단시설가구,집단시설가구,소계,소계,소계,소계
2,동별(1),동별(2),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),...,가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명)
3,동별(1),동별(2),소계,소계,남자,여자,소계,소계,남자,여자,...,남자,여자,소계,소계,남자,여자,소계,소계,남자,여자
4,합계,소계,3914820,9904312,4859535,5044777,3784490,9394807,4555632,4839175,...,7349,7239,883,96732,38361,58371,157129,267935,125103,142832


In [3]:
df.columns

Index(['동별(1)', '동별(2)', '2015', '2015.1', '2015.2', '2015.3', '2015.4',
       '2015.5', '2015.6', '2015.7',
       ...
       '2024.10', '2024.11', '2024.12', '2024.13', '2024.14', '2024.15',
       '2024.16', '2024.17', '2024.18', '2024.19'],
      dtype='object', length=202)

In [5]:
# df는 이미 불러온 DataFrame이라고 가정
# 1) 동별 컬럼 삭제
df = df.drop(columns=['동별(1)', '동별(2)'], errors='ignore')
df.head()

,2015,2015.1,2015.2,2015.3,2015.4,2015.5,2015.6,2015.7,2015.8,2015.9,...,2024.10,2024.11,2024.12,2024.13,2024.14,2024.15,2024.16,2024.17,2024.18,2024.19
0,총가구,총가구,총가구,총가구,일반가구,일반가구,일반가구,일반가구,집단가구,집단가구,...,집단가구,집단가구,집단가구,집단가구,집단가구,집단가구,외국인가구,외국인가구,외국인가구,외국인가구
1,소계,소계,소계,소계,소계,소계,소계,소계,비친족 6인이상 가구,비친족 6인이상 가구,...,비친족 6인이상 가구,비친족 6인이상 가구,집단시설가구,집단시설가구,집단시설가구,집단시설가구,소계,소계,소계,소계
2,가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),...,가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명),가구수 (가구),가구원수 (명),가구원수 (명),가구원수 (명)
3,소계,소계,남자,여자,소계,소계,남자,여자,소계,소계,...,남자,여자,소계,소계,남자,여자,소계,소계,남자,여자
4,3914820,9904312,4859535,5044777,3784490,9394807,4555632,4839175,1489,16753,...,7349,7239,883,96732,38361,58371,157129,267935,125103,142832


정규식 설명
정규식 r'^\d{4}(\.\d+)?$'는 문자열 전체가 네 자리 숫자(예: 2015)이거나 네 자리 숫자 뒤에 점과 하나 이상의 숫자(예: 2015.1, 2024.19)가 선택적으로 올 수 있음을 의미한다.

^: 문자열 시작을 뜻한다.

\d{4}: 숫자(digit) 4개가 정확히 연속해서 나옴을 뜻한다.

(\.\d+)?: 소수점 문자('.')와 하나 이상의 숫자(\d+)로 구성된 그룹이 0번 또는 1번 나타날 수 있음을 뜻한다(옵션).

$: 문자열 끝을 뜻한다.

예시 매칭: "2015" → 매칭, "2015.2" → 매칭, "15.1" → 불일치, "2015." → 불일치, "2015.2a" → 불일치

In [ ]:
# df: '구' 컬럼은 이미 drop 됨
# 예: df.columns => ['동별(1)', '동별(2)', '2015', '2015.1', '2015.2', ..., '2024.19']
import re
# 1) 연도 패턴 매칭: 'YYYY' 또는 'YYYY.x' 형태 컬럼 선택
year_cols = [c for c in df.columns if re.match(r'^\d{4}(\.\d+)?$', c)]


In [15]:
", ".join(word for word in year_cols[:10])

'2015, 2015.1, 2015.2, 2015.3, 2015.4, 2015.5, 2015.6, 2015.7, 2015.8, 2015.9'

In [23]:
# 2) 연도 키 추출 (ex: '2015.2' -> '2015')
col_year_map = {c: re.match(r'^(\d{4})', c).group(1) for c in year_cols}
", ".join(f'{key}:{items}' for key,items in list(col_year_map.items())[:10])

'2015:2015, 2015.1:2015, 2015.2:2015, 2015.3:2015, 2015.4:2015, 2015.5:2015, 2015.6:2015, 2015.7:2015, 2015.8:2015, 2015.9:2015'

In [30]:
# 3) 같은 연도끼리 합산: 먼저 연도별로 빈 프레임 만들기
years = sorted({v for v in col_year_map.values()})  # 중복을 제거한 년도 만들기
year_df = pd.DataFrame(index=df.index) #먼저 연도별로 빈 프레임 만들기

In [31]:
for y in years:
    cols_for_y = [col for col, yy in col_year_map.items() if yy == y]
    # NaN 안전하게 합: sum(axis=1, skipna=True)
    year_df[y] = df[cols_for_y].sum(axis=1)

In [32]:
# 4) 기존의 연도 관련 상세 컬럼 제거하고 연도 합계 붙이기
#    (원하면 동별 식별자 컬럼은 유지)
non_year_cols = [c for c in df.columns if c not in year_cols]
result = pd.concat([df[non_year_cols].reset_index(drop=True), year_df.reset_index(drop=True)], axis=1)

In [33]:
# 5) 연도 컬럼을 정수형으로 정리 (컬럼명으로 사용)
#    현재 year_df의 컬럼은 문자열 '2015' 등임. 필요시 int로 변환 가능:
result.columns = [int(c) if re.match(r'^\d{4}$', str(c)) else c for c in result.columns]

# 결과 확인
print(result.head())

                                                2015  \
0  총가구총가구총가구총가구일반가구일반가구일반가구일반가구집단가구집단가구집단가구집단가구집단...   
1  소계소계소계소계소계소계소계소계비친족 6인이상 가구비친족 6인이상 가구비친족 6인이상...   
2  가구수 (가구)가구원수 (명)가구원수 (명)가구원수 (명)가구수 (가구)가구원수 (...   
3           소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자   
4  3914820990431248595355044777378449093948074555...   

                                                2016  \
0  총가구총가구총가구총가구일반가구일반가구일반가구일반가구집단가구집단가구집단가구집단가구집단...   
1  소계소계소계소계소계소계소계소계비친족 6인이상 가구비친족 6인이상 가구비친족 6인이상...   
2  가구수 (가구)가구원수 (명)가구원수 (명)가구원수 (명)가구수 (가구)가구원수 (...   
3           소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자   
4  3915023980550647991155006391378470593150754510...   

                                                2017  \
0  총가구총가구총가구총가구일반가구일반가구일반가구일반가구집단가구집단가구집단가구집단가구집단...   
1  소계소계소계소계소계소계소계소계비친족 6인이상 가구비친족 6인이상 가구비친족 6인이상...   
2  가구수 (가구)가구원수 (명)가구원수 (명)가구원수 (명)가구수 (가구)가구원수 (...   
3           소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자소계소계남자여자   
4  3948850974187147576424984229381326092395174

In [34]:
# 2) 연도 관련 컬럼 선택(예: '2015', '2015.1', ..., '2024.19' 등 숫자로 시작하는 컬럼)
year_cols = [c for c in df.columns if re.match(r'^\d{4}(\.\d+)?$', c)]

In [35]:
# 3) melt로 와이드 -> 롱 변환
#    variable_name은 원래 컬럼 이름(예: '2015.1')을 담고, value_name은 해당 값
long = df.melt(id_vars=[c for c in df.columns if c not in year_cols],
               value_vars=year_cols,
               var_name='year_col',
               value_name='value')

In [36]:
# 4) 필요하면 'year_col'에서 실제 연도만 추출 (예: '2015.1' -> '2015' 또는 '2015.1'을 유지)
#    (아래는 소수점 앞 숫자만 연도로 추출하는 예)
long['year'] = long['year_col'].str.extract(r'^(\d{4})').astype(int)

In [37]:
# 5) 불필요한 컬럼 제거 및 정렬
long = long.drop(columns=['year_col'])
long = long.reset_index(drop=True)

# 결과 확인
print(long.head())

      value  year
0       총가구  2015
1        소계  2015
2  가구수 (가구)  2015
3        소계  2015
4   3914820  2015


groupby로 간단히 합치기

In [ ]:
import pandas as pd 
import re
df = pd.read_csv('seoul_gagu.csv')
df.size

# 가정: df는 원본 DataFrame (동/구 컬럼은 이미 제거하거나 유지할 수 있음)
df = df.drop(columns=['동별(1)', '동별(2)'], errors='ignore')
# 1) 컬럼명에서 연도(앞 4자리) 추출 (매칭되지 않으면 NaN)
col_year = df.columns.to_series().str.extract(r'^(\d{4})')[0]

# 2) 연도 형태로 매칭된 컬럼들만 같은 연도끼리 합산
df_year = df.loc[:, col_year.notna()].groupby(col_year[col_year.notna()], axis=1).sum()

# 3) 연도 외(식별자 등) 컬럼이 있다면 합쳐서 최종 결과 생성
non_year = df.loc[:, col_year.isna()]
result = pd.concat([non_year.reset_index(drop=True), df_year.reset_index(drop=True)], axis=1)

# 4) (선택) 연도 컬럼을 정수형으로 바꾸려면
result.columns = [int(c) if isinstance(c, str) and c.isdigit() else c for c in result.columns]




In [41]:
# 결과 확인
#print(result.head())
print(result.columns)

Index([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype='int64')
